## Assignment 1

In this assignment you are expected to implements Python functions that estimate some mathematical constants and operators. The assignmnet focuses on your Python expertiese on recursive functions, loops, `if` statements, data structures, and basic operators.  

In [1]:
import numpy as np

We are going to implement some functions/constants that our calculator / `numpy` / Google has.

#### Exercise 1: Write a function that calculates the factorial of a number `n`

The factorial of a number is represented by using the exclamation sign, for example, the factorial of $3$ is represented as $3!$. You can see how the factorial of a number N is calculated in the following examples:

$$1! = 1$$

$$2! = 2 x 1 = 2$$

$$3! = 3 x 2 x 1 = 6$$

$$4! = 4 x 3 x 2 x 1 = 24$$

The general formula is:

$$n! = n (n-1)!$$

$$1! = 1$$

$$0! = 1$$

You can use either an iterative approach (with for or while loops) or a recursive approach.

In [2]:
def fact (n):
    #YOUR CODE HERE
    result = 1
    for i in range(n, 0, -1):
        result *= i
    return result

# def fact_r(n):
#     if n == 0 or n == 1:
#         return 1
#     else :
#         return n * fact_r(n - 1)

In [3]:
fact(5),fact(6),fact(7),fact(10)

(120, 720, 5040, 3628800)

#### Exercise 2: Approximate number e

Euler's number, the number `e` is a constant number which is the base of the natural logarithm ($ln$). It is approximately 2.71828 and it can be calculated as the sum of the following infinite series:

$$e \approx \sum _ { k = 0 } ^ { \infty } \frac { 1 } { k ! } = \frac{1}{1} + \frac{1}{1} + \frac{1}{1x2}+ \frac{1}{1x2x3}+ \frac{1}{1x2x3x4} + \ldots$$

We know that infinity is very big, but, we can approximate the number, let's say, until $k=100$. Can you?

In [4]:
def approximate_e ():
    #YOUR CODE HERE 新知识，python的int类型支持无限大，换句话说就是，这里不必考虑溢出的问题。
    temp = 1.0 # temp is the ith element of the infinite series
    e = 1.0 # let's skip the first term of the infinite series
    for i in range(1, 101):
        e += temp / i
        temp = temp / i
    return e

In [5]:
e = approximate_e()
e

2.7182818284590455

#### Additional/Optional exercise:

What is the difference between the approximate values of e with $k=20$ and $k=21$? How is that difference as $k$ becomes bigger?

In [6]:
#YOUR CODE HERE (OPTIONAL)
def approximate_e(k):
    temp = 1.0
    e = 1.0 
    for i in range(1, k + 1):
        e += temp / i
        temp = temp / i
        print(f"The difference between k={i - 1} and k={i} is", temp)
    return e
approximate_e(21)
# As k goes bigger, the differences become smaller

The difference between k=0 and k=1 is 1.0
The difference between k=1 and k=2 is 0.5
The difference between k=2 and k=3 is 0.16666666666666666
The difference between k=3 and k=4 is 0.041666666666666664
The difference between k=4 and k=5 is 0.008333333333333333
The difference between k=5 and k=6 is 0.001388888888888889
The difference between k=6 and k=7 is 0.0001984126984126984
The difference between k=7 and k=8 is 2.48015873015873e-05
The difference between k=8 and k=9 is 2.7557319223985893e-06
The difference between k=9 and k=10 is 2.7557319223985894e-07
The difference between k=10 and k=11 is 2.505210838544172e-08
The difference between k=11 and k=12 is 2.08767569878681e-09
The difference between k=12 and k=13 is 1.6059043836821616e-10
The difference between k=13 and k=14 is 1.1470745597729726e-11
The difference between k=14 and k=15 is 7.647163731819817e-13
The difference between k=15 and k=16 is 4.779477332387386e-14
The difference between k=16 and k=17 is 2.811457254345521e-15
The 

2.7182818284590455

#### Exercise 3: Approximate Square root using the Babylonian method

Now we are interested in calculating the square root of any number. It may seem trivial, but it is not so easy. Think, for instance, which is the square root of $60$?

[This wiki article](https://en.wikipedia.org/wiki/Methods_of_computing_square_roots) shows different approaches!

In this exercise you have to implement the Babylonian method, which calculates the square roots quite well. As with the number `e`, this result is reached when the function reaches infinity. Here you should also work for $k=100$ iterations.

The method initializes $x_0$ with the approximate square root of $S$. In our case, in order to ensure that everybody gets the same answer, we will initialize the value with $S$.


$$x _ { 0 } = S $$

$$x _ { k + 1 } = \frac { 1 } { 2 } \left( x _ { k } + \frac { S } { x _ { k } } \right) $$

$$\sqrt { S } = \lim _ { k \rightarrow \infty } x _ { k }$$


In [7]:
def appr_sqrt(S, init = None):
    #YOUR CODE HERE
    if init:
        x = init
    else:
        x = S
    for i in range(1, 101):
        x = 1.0/2*(x + S / x)
    return x

In [8]:
appr_sqrt(150)

12.24744871391589

#### Additional/Optional exercise:

What happens if we initialize the $x_0$ with different values?

In [9]:
#YOUR CODE HERE (OPTIONAL)
print(appr_sqrt(150, 0))
print(appr_sqrt(150, 1))
print(appr_sqrt(150, 2))
print(appr_sqrt(150, 4))
print(appr_sqrt(150, 1024))
print(appr_sqrt(150, 10000))
# The result is the same at this floating-point precision.

12.24744871391589
12.24744871391589
12.24744871391589
12.24744871391589
12.24744871391589
12.24744871391589


#### Exercise 4: Approximate the number $\pi$

The number $\pi$ is an amazing number! It was originally defined as the ratio of a circle's circumference to its diameter, and now it has some other equivalent definitions.

We saw an approximation for estimating the number by using random numbers (this is also known as a Montecarlo simulation), but today we will implement another formula for approximating it. Here it is:

$$v a l = \sum _ { k = 0 } ^ { \infty } \frac { (- 3) ^ { - k } } { 2 k + 1 }$$

$$\pi \approx val \cdot \sqrt { 12 }$$

Again, this is an infinite series, which should approximate the number fairly well for high numbers. But, as in previous cases, in order to have a coherent result, we will calculate the value of $\pi$ after $k=100$ iterations, and using the previously created `appr_sqrt` function. 

In [10]:
def appr_pi ():
    #YOUR CODE HERE
    val = 1
    temp = 1
    for k in range(1, 101):
        temp = temp / (-3)
        val += temp / (2 * k + 1)
    return val * appr_sqrt(12)

In [11]:
appr_pi()

3.141592653589794

#### Exercise 5: Matrix multiplication with lists

We know how important matrix multiplication is for machine learning, deep learning and algebra. We also know that there is a wonderful function in the package `numpy` that can do that for us (`np.dot`). 

In this excercise you are asked to implement a matrix multiplication function `matrix_multiply(m1, m2)` that takes two numpy matrices as arguments and returns the matrix product of these in a new matrix. The function should work element by element without calling any vectorized method or the `np.dot`. Although numpy library already implements matrix multiplication, your implementation cannot use any part of the numpy library, with the exceptions noted below:

  * `.shape` to get the size of a matrix;
  * `np.zeros((n, m))` to create a new $n$ by $m$ matrix; and
  * the `[i, j]` indexing syntax to retrieve or set the value of cell $(i, j)$.

Below are defined matrices $X, Y$ and $Z$.

Implement the function matrix_multiply(m1, m2) and test it by computing the products $M_1M_2$ and $M_3M_4$.


In [12]:
X = np.array([[6,7,7,8],[4,3,3,3]])
Y = np.array([[1,3,5],[2,4,9],[8,9,0],[3,3,3]])
Z = np.array([[10,13,45,11],[65,24,42,98],[1,1,2,0],[4,2,1,2]])

In [13]:
X.shape,Y.shape,Z.shape

((2, 4), (4, 3), (4, 4))

In [14]:
def matrix_multiply(m1, m2):
    # Inner dimensions need to match. 
    # Otherwise, matrix multiplication is not defined
    assert m1.shape[1] == m2.shape[0]
    
    # Create output matrix
    out = np.zeros((m1.shape[0], m2.shape[1]), dtype=m1.dtype)
    
    # Each cell is the dot product between an `m1` row vector and a `m2` column vector, 
    # which have the same size
    component_vector_size = m1.shape[1]
    
    # Fill it, cell by cell
    #YOUR CODE HERE
    for i_m1_row in range(m1.shape[0]):
        for i_m2_col in range(m2.shape[1]):
            product = 0
            for i in range(component_vector_size):
                product += m1[i_m1_row, i] * m2[i, i_m2_col]
            out[i_m1_row, i_m2_col] = product
                
    return out

In [15]:
matrix_multiply(X,Y)

array([[100, 133, 117],
       [ 43,  60,  56]])

In [16]:
matrix_multiply(X,Z)

array([[554, 269, 586, 768],
       [250, 133, 315, 344]])

In [17]:
matrix_multiply(Z,Y)

array([[429, 520, 200],
       [743, 963, 835],
       [ 19,  25,  14],
       [ 22,  35,  44]])

#### Additional exercise:

Implement matrix multiplication using only lists, without using any options that the `numpy` package gives you. 

In [18]:
#YOUR CODE HERE (OPTIONAL)
X = [[6,7,7,8],[4,3,3,3]]
Y = [[1,3,5],[2,4,9],[8,9,0],[3,3,3]]
Z = [[10,13,45,11],[65,24,42,98],[1,1,2,0],[4,2,1,2]]

def matrix_mult(m1, m2):
    # Inner dimensions need to match. 
    # Otherwise, matrix multiplication is not defined
    assert len(m1[0]) == len(m2)
    
    # Create output matrix
    out = [[0 for j in range(len(m2[1]))] for i in range(len(m1))]
    
    # Each cell is the dot product between an `m1` row vector and a `m2` column vector, 
    # which have the same size
    component_vector_size = len(m1[0])
    
    # Fill it, cell by cell
    for i_m1_row in range(len(m1)):
        for i_m2_col in range(len(m2[1])):
            product = 0
            for i in range(component_vector_size):
                product += m1[i_m1_row][i] * m2[i][i_m2_col]
            out[i_m1_row][i_m2_col] = product
                
    return out

print(matrix_mult(X, Y))
print(matrix_mult(X, Z))
print(matrix_mult(Z, Y))

[[100, 133, 117], [43, 60, 56]]
[[554, 269, 586, 768], [250, 133, 315, 344]]
[[429, 520, 200], [743, 963, 835], [19, 25, 14], [22, 35, 44]]
